# Generated by Django 5.0 on 2024-02-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GigModel',
        ),
    ]
