# Generated by Django 5.0 on 2024-02-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gig', '0002_delete_gigmodel'),
        ('registration', '0002_category_alter_user_email_alter_worker_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='registration.category')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='registration.worker')),
            ],
        ),
    ]
