# Generated by Django 5.0 on 2024-02-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='image',
            field=models.ImageField(default=False, upload_to=None),
        ),
    ]
