# Generated by Django 5.0 on 2024-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0005_alter_gig_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
