# Generated by Django 5.0 on 2024-02-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0006_alter_gig_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='Category',
            new_name='category',
        ),
    ]
