# Generated by Django 5.0 on 2024-03-16 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('jobposting', '0011_alter_jobrequirement_image'),
        ('registration', '0008_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktitle', models.TextField()),
                ('workdescription', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('status', models.CharField(default='applied', max_length=50)),
                ('image', models.ImageField(null=True, upload_to='image/gigProposal')),
                ('payamount', models.IntegerField(null=True)),
                ('paymethod', models.CharField(max_length=50, null=True)),
                ('acceptedate', models.DateField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigp_roposalcategory', to='category.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergig_Proposal', to='registration.user')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_gigProposal', to='registration.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('gigproposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_Proposalwork', to='gighire.gigproposal')),
                ('jobproposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_workratingwork', to='jobposting.jobrequirement')),
                ('rateduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userratedwork', to='registration.user')),
                ('rateuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userratingwork', to='registration.user')),
            ],
        ),
    ]
