# Generated by Django 5.0 on 2024-03-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobposting', '0004_delete_jobapply'),
        ('registration', '0003_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(default='inprogress', max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapp_job', to='jobposting.jobrequirement')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapp_worker', to='registration.worker')),
            ],
        ),
    ]
