# Generated by Django 5.0 on 2024-03-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
        ('registration', '0003_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(default='applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapp_worker', to='registration.workerprofile'),
        ),
    ]
