# Generated by Django 5.0 on 2024-03-02 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_alter_proposal_status_alter_proposal_worker'),
        ('registration', '0003_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapp_worker', to='registration.worker'),
        ),
    ]
