# Generated by Django 5.0 on 2024-03-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_alter_proposal_worker'),
        ('registration', '0005_alter_user_age_alter_user_citizenship_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapp_worker', to='registration.user'),
        ),
    ]
