# Generated by Django 5.0 on 2024-03-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_alter_proposal_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
