# Generated by Django 5.0 on 2024-03-06 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0009_alter_jobrequirement_isfeatured'),
        ('proposal', '0005_proposal_accepted_at'),
        ('registration', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobreqjob', to='jobposting.jobrequirement'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobreqworker', to='registration.user'),
        ),
    ]
