# Generated by Django 5.0 on 2024-03-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_alter_proposal_job_alter_proposal_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='amountPayed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='paymethod',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='accepted_at',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
