# Generated by Django 5.0 on 2024-01-03 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('isKycVerified', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('isKycVerified', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('rating', models.IntegerField()),
                ('citizenship_np', models.CharField(max_length=50, null=True)),
                ('User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('rating', models.IntegerField()),
                ('citizenship_np', models.CharField(max_length=50, null=True)),
                ('worker', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.worker')),
            ],
        ),
    ]
