# Generated by Django 5.0 on 2024-02-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0008_alter_gig_category'),
        ('jobposting', '0002_alter_jobrequirement_category'),
        ('registration', '0002_category_alter_user_email_alter_worker_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
