# Generated by Django 5.0 on 2024-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='worker',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='street_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='citizenship_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='worker',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='street_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
        migrations.DeleteModel(
            name='WorkerProfile',
        ),
    ]
