# Generated by Django 5.0 on 2024-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_workerprofile_worker_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='citizenship_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='worker',
            name='street_name',
            field=models.CharField(max_length=50),
        ),
    ]
