# Generated by Django 5.0 on 2024-03-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('gig', '0009_alter_gig_worker'),
        ('proposal', '0004_alter_proposal_worker'),
        ('registration', '0005_alter_user_age_alter_user_citizenship_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='client', max_length=15),
        ),
    ]
