# Generated by Django 5.0 on 2024-02-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_category_alter_user_email_alter_worker_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.IntegerField()),
                ('isFeatured', models.BooleanField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('location', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobreq_category', to='registration.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobreq_user', to='registration.user')),
            ],
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapp_worker', to='registration.worker')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapp_job', to='jobposting.jobrequirement')),
            ],
        ),
    ]
