# Generated by Django 5.0 on 2024-03-01 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0002_alter_jobrequirement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequirement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='jobStatus',
            field=models.CharField(default='inprogress', max_length=50),
        ),
    ]
