# Generated by Django 5.0 on 2024-03-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0003_jobrequirement_created_at_jobrequirement_jobstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApply',
        ),
    ]
