# Generated by Django 5.0 on 2024-03-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0004_delete_jobapply'),
        ('registration', '0003_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobreq_user', to='registration.userprofile'),
        ),
    ]
