# Generated by Django 5.0 on 2024-03-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('jobposting', '0009_alter_jobrequirement_isfeatured'),
        ('registration', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobreqcategory', to='category.category'),
        ),
        migrations.AlterField(
            model_name='jobrequirement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobrequser', to='registration.user'),
        ),
    ]
